package cz.bliksoft.javautils.net.http;

public enum HTTPErrorCodes {
	INFO_CONTINUE(100), //
	INFO_SWITCH_PROTOCOLS(101), //

	OK(200), //
	OK_CREATED(201), //
	OK_ACCEPTED(202), //
	OK_NON_AUTHORITATIVE_INFORMATION(203), //
	OK_NO_CONTENT(204), //
	OK_RESET_CONTENT(205), //
	OK_PARTIAL_CONTENT(206), //

	REDIR_MULTIPLE_CHOICES(300), //
	REDIR_MODEV_PERMANENTLY(301), //
	REDIR_MOVED_TEMPORARILY(302), //
	REDIR_SEE_OTHER(303), //
	REDIIR_NOT_MODIFIED(304), //
	REDIR_USE_PROXY(305), //

	CLIENT_BAD_REQUEST(400), //
	CLIENT_UNAUTHORIZED(401), //
	CLIENT_PAYMENT_REQUIRED(402), //
	CLIENT_FORBIDDEN(403), //
	CLIENT_NOT_FOUND(404), //
	CLIENT_METHOD_NOT_ALLOWED(405), //
	CLIENT_NOT_ACCEPTABLE(406), //
	CLIENT_PROXY_AUTHENTICATION_REQUIRED(407), //
	CLIENT_REQUEST_TIMEOUT(408), //
	CLIENT_CONFLICT(409), //
	CLIENT_GONE(410), //
	CLIENT_LENGTH_REQUIRED(411), //
	CLIENT_RECONDITION_FAILED(412), //
	CLIENT_REQUEST_ENTITY_TOO_LARGE(413), //
	CLIENT_REQUEST_URI_TOO_LONG(414), //
	CLIENT_UNSUPPORTED_MEDIA_TYPE(415), //

	SERVER_INTERNAL_SERVER_ERROR(500), //
	SERVER_NOT_IMPLEMENTED(501), //
	SERVER_BAD_GATEWAY(502), //
	SERVER_SERVICE_UNAVAILABLE(503), //
	SERVER_GATEWAY_TIMEOUT(504), //
	SERVER_HTTP_VERSION_NOT_SUPPORTED(505)//
	;

	private int value;

	private HTTPErrorCodes(int code) {
		this.value = code;
	}

	public int getValue() {
		return value;
	}
}
